// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckChoco():Promise<string>;

export function CpuFreq():Promise<Array<number>>;

export function CpuInfo():Promise<Array<string>>;

export function GetCPUFrequencies():Promise<Array<number>>;

export function GetMemUsage():Promise<Array<any>>;

export function GetStorage():Promise<Array<any>>;

export function GpuInfo():Promise<Array<string>>;

export function Install():Promise<string>;

export function InstallApp(arg1:string):Promise<string>;

export function Memory():Promise<string>;

export function OsInfo():Promise<Array<string>>;

export function RenderAppsList():Promise<string>;

export function Search(arg1:string):Promise<string>;
