// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckChoco() {
  return window['go']['main']['App']['CheckChoco']();
}

export function CpuFreq() {
  return window['go']['main']['App']['CpuFreq']();
}

export function CpuInfo() {
  return window['go']['main']['App']['CpuInfo']();
}

export function GetCPUFrequencies() {
  return window['go']['main']['App']['GetCPUFrequencies']();
}

export function GetMemUsage() {
  return window['go']['main']['App']['GetMemUsage']();
}

export function GetStorage() {
  return window['go']['main']['App']['GetStorage']();
}

export function GpuInfo() {
  return window['go']['main']['App']['GpuInfo']();
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function InstallApp(arg1) {
  return window['go']['main']['App']['InstallApp'](arg1);
}

export function Memory() {
  return window['go']['main']['App']['Memory']();
}

export function OsInfo() {
  return window['go']['main']['App']['OsInfo']();
}

export function RenderAppsList() {
  return window['go']['main']['App']['RenderAppsList']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
